##@ Development

BINARY := agent-manager

.PHONY: build-linux-amd64
build-linux-amd64: ## Build the linux/amd64 binary the Dockerfile expects; version and commit come from the Go build info (the tag at HEAD, else dev).
	CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -trimpath -ldflags "-s -w" -o $(BINARY)-linux-amd64 .

.PHONY: docker-build
docker-build: build-linux-amd64 ## Build a local dev image (TAG=agent-manager:dev).
	docker build --build-arg TARGETOS=linux --build-arg TARGETARCH=amd64 -t $(or $(TAG),agent-manager:dev) .

.PHONY: test-race
test-race: ## Run tests with the race detector.
	go test -race ./...

##@ kagent

# Commit of giantswarm/kagent-upstream (tag v1.3.1) the kagent.api.v1alpha1
# protos under hack/kagent-proto/ are copied from. Bump it, run `make
# generate-kagent`, and commit hack/kagent-proto/ and internal/kagent/gen/
# together.
KAGENT_PROTO_REPO ?= https://github.com/giantswarm/kagent-upstream.git
KAGENT_PROTO_COMMIT ?= 1b166604dfa12713cfd8ca50697518678df2cf07
KAGENT_PROTO_FILES := common runtime sessions

.PHONY: generate-kagent
generate-kagent: ## Refresh the kagent protos from KAGENT_PROTO_COMMIT and regenerate internal/kagent/gen.
	@tmp=$$(mktemp -d) && git clone -q --filter=blob:none --no-checkout $(KAGENT_PROTO_REPO) $$tmp \
	  && git -C $$tmp checkout -q $(KAGENT_PROTO_COMMIT) -- proto/kagent/api/v1alpha1 proto/buf.lock \
	  && for f in $(KAGENT_PROTO_FILES); do cp $$tmp/proto/kagent/api/v1alpha1/$$f.proto hack/kagent-proto/kagent/api/v1alpha1/; done \
	  && grep -A2 'bufbuild/protovalidate' $$tmp/proto/buf.lock | sed '1i # Generated by buf. DO NOT EDIT.\nversion: v2\ndeps:' > hack/kagent-proto/buf.lock \
	  && rm -rf $$tmp
	cd hack/kagent-proto && PATH="$$(go env GOPATH)/bin:$$PATH" buf generate
	# The repository formats every Go file with goimports; protoc-gen-go groups
	# imports differently, so the generated files are formatted once here.
	go run golang.org/x/tools/cmd/goimports@v0.50.0 -local github.com/giantswarm/agent-manager -w internal/kagent/gen
	sed -i 's/^KAGENT_PROTO_COMMIT: .*/KAGENT_PROTO_COMMIT: $(KAGENT_PROTO_COMMIT)/' hack/kagent-proto/README.md

##@ Helm

.PHONY: helm-lint
helm-lint: ## Lint the chart.
	helm lint helm/agent-manager

.PHONY: helm-template
helm-template: ## Render the chart with defaults.
	helm template agent-manager helm/agent-manager

HELM_UNITTEST_VERSION := 1.0.3

.PHONY: helm-test
helm-test: helm-lint helm-unittest ## Run every chart check (what the chart-test CI job runs).

.PHONY: helm-unittest
helm-unittest: helm-plugin-unittest ## Run the helm-unittest suites in helm/agent-manager/tests/.
	helm unittest helm/agent-manager

.PHONY: helm-plugin-unittest
helm-plugin-unittest:
	@helm plugin list | grep -q '^unittest' || helm plugin install https://github.com/helm-unittest/helm-unittest --version $(HELM_UNITTEST_VERSION)

.PHONY: helm-schema
helm-schema: ## Regenerate values.schema.json (needs the helm schema plugin and schemalint).
	helm schema --config helm/agent-manager/.schema.yaml
	python3 -c 'import json,sys; h=lambda o: {**{k:v for k,v in o.items() if k!="additionalProperties"},"unevaluatedProperties":False} if ("$$ref" in o and o.get("additionalProperties") is False) else o; p=sys.argv[1]; f=open(p,encoding="utf-8"); d=json.load(f,object_hook=h); f.close(); f=open(p,"w",encoding="utf-8"); json.dump(d,f); f.close()' helm/agent-manager/values.schema.json
	schemalint normalize helm/agent-manager/values.schema.json -o helm/agent-manager/values.schema.json --force

.PHONY: helm-docs
helm-docs: ## Regenerate the chart README.
	helm-docs --chart-search-root=helm --sort-values-order=file
